-- ==============================================================================
-- 🚀 MIGRATION: ผูกสินค้าเข้ากับรูปภาพ Collection / Journal
-- นำคำสั่ง SQL นี้ไปรันใน Supabase SQL Editor ได้เลยครับ
-- ==============================================================================

-- 1. สร้างตารางเชื่อม journal_image_products
CREATE TABLE IF NOT EXISTS public.journal_image_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_image_id BIGINT NOT NULL REFERENCES public.journal_images(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(journal_image_id, product_id)
);

-- 2. สร้าง Index เพื่อให้ค้นหาและโหลดข้อมูลได้รวดเร็วระดับ Millisecond
CREATE INDEX IF NOT EXISTS idx_jip_image_id ON public.journal_image_products(journal_image_id);
CREATE INDEX IF NOT EXISTS idx_jip_product_id ON public.journal_image_products(product_id);

-- 3. ตั้งค่าความปลอดภัย Row Level Security (RLS)
ALTER TABLE public.journal_image_products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read journal_image_products" ON public.journal_image_products;
CREATE POLICY "Public read journal_image_products" ON public.journal_image_products 
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin all journal_image_products" ON public.journal_image_products;
CREATE POLICY "Admin all journal_image_products" ON public.journal_image_products 
  FOR ALL USING (true);
