-- ==============================================================================
-- 🚀 MIGRATION: เปลี่ยน IDENTITY Columns จาก GENERATED ALWAYS เป็น GENERATED BY DEFAULT
-- แก้ไขปัญหา: Restore / Backup Upsert ติด Error:
-- "cannot insert a non-DEFAULT value into column 'id'"
-- ==============================================================================

ALTER TABLE IF EXISTS public.journal_images ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE IF EXISTS public.stock_audits ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE IF EXISTS public.stock_audit_scans ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE IF EXISTS public.stock_audit_items ALTER COLUMN id SET GENERATED BY DEFAULT;
